### ISSUE TITLE
Wiggle not working?

### ISSUE THREAD

**Issue by Alf0nso** [miguelgrinberg/anaglyph.py#1]
Hey, I was going to try the wiggle function just for the fun of it and it doesn't look like it's working...

Error:
Traceback (most recent call last):
  File "C:\...\env\anaglyph.py\anaglyph.py", line 141, in <module>
    main()
  File "C:\...\env\anaglyph.py\anaglyph.py", line 138, in main
    make_wiggle3d(leftImage, rightImage, options.color, stereoPath)
  File "C:\...\env\anaglyph.py\anaglyph.py", line 69, in make_wiggle3d
    writeGif(path, [left, right], 0.1, True, False, 0, False, 2)
  File "C:\...\env\anaglyph.py\images2gif.py", line 575, in writeGif
    gifWriter.writeGifToFile(fp, images, duration, loops, xy, dispose)
  File "C:\...\env\anaglyph.py\images2gif.py", line 435, in writeGifToFile
    fp.write(header)
TypeError: a bytes-like object is required, not 'str'

I used: anaglyph.py -w left_1.jpg right_1.jpg final_3.gif in windows 10 cmd terminal

I tried to convert the header to byte like object and after running again, it gave me another error saying that in "fp.write(globalPalette)", globalPalette needed to be byte-like object and not NoneType, I assume here that changing NoneType to byte won't make anything....

Another note, the pictures were taken with an iphone, and not with an actual camera, maybe that's the problem?

Anyway very nice script/program

**Comment by miguelgrinberg** [comment]
I haven't touched this script in the last 7 years. Wow.

The problem was a Python 2 vs. Python 3 issue. I have made some updates to the script, let me know if it works better for you now. I was able to create a wiggle gif from two jpegs taken with my phone, so I think this should be good for at least another 7 years. :)
