### ISSUE TITLE
hi, I wonder the left/right images used in your repo are captured or generated?

### ISSUE THREAD

**Issue by lvZic** [miguelgrinberg/anaglyph.py#2]
I just used left image to generate right image by depth based image render algorithm. However, the merged analygh image seems not have stereo effect. I found your result has a good performance. So i wonder how you get the left and right image pair?

**Comment by miguelgrinberg** [comment]
My stereo examples are all captured with a camera.

**Comment by lvZic** [comment]
> My stereo examples are all captured with a camera.

Following are left&right images GIF by DBIR algorithm and your repo. 
![3dtv_0](https://github.com/miguelgrinberg/anaglyph.py/assets/7788572/25d574fb-640c-4165-ad20-7c1eee78d235)

![3dtv](https://github.com/miguelgrinberg/anaglyph.py/assets/7788572/0be447b0-0f31-45ef-8f7e-d938fb1c4834)

Obviously, the motion between captured one and generated one are different, and the former one has rotation. I think maybe this is the reason harm the stereo performance ? 
Can u give me some advice about improving the 2d-3d stereo performance? thanks.

**Comment by miguelgrinberg** [comment]
I'm sorry but I have no experience generating 3d images. I just shoot the pictures with a camera, it's not interesting to me to do a fake 3d effect.
